### PR TITLE
add parameters to dynamodb read and write capacity

### PR DESCRIPTION
**Pull request by acharp**
This change is [Reviewable](https://reviewable.io/reviews/humilis/humilis-secrets-vault/1)

### CODE REVIEW

**Comment by germangh** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/integration/secrets-vault.yaml, line 31 \[r1\]](https://reviewable.io:443/reviews/humilis/humilis-secrets-vault/1#-KHLA5FRg4elOjfDwx1F:-KHLA5FRg4elOjfDwx1G:26574375) ([raw file](https://github.com/humilis/humilis-secrets-vault/blob/1deee858ac01da8e7a90b480f1a6c0405f63bfcd/tests/integration/secrets-vault.yaml#L31)):*
> ```YAML
>           layer_type: secrets-vault
>           associated_processors: ["filter"]
>           dynamodb_capacity: {read: 5, write: 1}        
> ```

Remove spaces at the end of the line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/humilis/humilis-secrets-vault/1)*

**Comment by acharp** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/integration/secrets-vault.yaml, line 31 \[r1\]](https://reviewable.io:443/reviews/humilis/humilis-secrets-vault/1#-KHLA5FRg4elOjfDwx1F:-KHP3Ie1dpLVIxQKttRn:-178080538) ([raw file](https://github.com/humilis/humilis-secrets-vault/blob/1deee858ac01da8e7a90b480f1a6c0405f63bfcd/tests/integration/secrets-vault.yaml#L31)):*
<details><summary><i>Previously, germangh (German Gomez-Herrero) wrote…</i></summary>
> Remove spaces at the end of the line.</details>
Done, I'll add a vim plugin to avoid that happens again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/humilis/humilis-secrets-vault/1)*

**Comment by germangh** [comment]
Reviewed 1 of 3 files at r1.
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/humilis/humilis-secrets-vault/1)*

**Comment by germangh** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/humilis/humilis-secrets-vault/1)*

**Pull request merged**
